/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author PC
 */
public class Atividade05 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Atividade05.class.getName());

    /**
     * Creates new form Atividade05
     */
    public Atividade05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sldInicio = new javax.swing.JSlider();
        lblInicio = new javax.swing.JLabel();
        lblInicioValor = new javax.swing.JLabel();
        sldFinal = new javax.swing.JSlider();
        lblFinalValor = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        sldPulo = new javax.swing.JSlider();
        lblPulo = new javax.swing.JLabel();
        lblPuloValor = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        txtPainel = new javax.swing.JScrollPane();
        txtAreaPainel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sldInicio.setMajorTickSpacing(10);
        sldInicio.setMaximum(5);
        sldInicio.setMinimum(1);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });

        lblInicio.setText("Inicio");

        lblInicioValor.setText("5");

        sldFinal.setMajorTickSpacing(5);
        sldFinal.setMaximum(50);
        sldFinal.setMinimum(5);
        sldFinal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFinalStateChanged(evt);
            }
        });

        lblFinalValor.setText("50");

        lblFinal.setText("Final");

        sldPulo.setMajorTickSpacing(10);
        sldPulo.setMaximum(5);
        sldPulo.setMinimum(1);
        sldPulo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPuloStateChanged(evt);
            }
        });

        lblPulo.setText("Pulo");

        lblPuloValor.setText("5");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        txtAreaPainel.setColumns(20);
        txtAreaPainel.setRows(5);
        txtPainel.setViewportView(txtAreaPainel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldPulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuloValor)
                            .addComponent(lblInicioValor)
                            .addComponent(lblFinalValor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnIniciar)))
                .addGap(18, 18, 18)
                .addComponent(txtPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInicioValor)
                    .addComponent(lblInicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinalValor)
                    .addComponent(lblFinal))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldPulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPulo)
                    .addComponent(lblPuloValor))
                .addGap(33, 33, 33)
                .addComponent(btnIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(txtPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
        // TODO add your handling code here:
        lblInicioValor.setText("" + sldInicio.getValue());
    }//GEN-LAST:event_sldInicioStateChanged

    private void sldFinalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFinalStateChanged
        // TODO add your handling code here:
        lblFinalValor.setText("" + sldFinal.getValue());
    }//GEN-LAST:event_sldFinalStateChanged

    private void sldPuloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPuloStateChanged
        // TODO add your handling code here:
        lblPuloValor.setText("" + sldPulo.getValue());
    }//GEN-LAST:event_sldPuloStateChanged

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        int inicio = sldInicio.getValue();
        int fim = sldFinal.getValue();
        int pulo = sldPulo.getValue();
        
        while(inicio < fim){
            txtAreaPainel.insert( String.valueOf(inicio) + "\n" , txtAreaPainel.getCaretPosition());
            inicio = inicio + pulo;
        }
        txtAreaPainel.insert( String.valueOf(fim) + "\n" , txtAreaPainel.getCaretPosition());
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Atividade05().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblFinalValor;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicioValor;
    private javax.swing.JLabel lblPulo;
    private javax.swing.JLabel lblPuloValor;
    private javax.swing.JSlider sldFinal;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPulo;
    private javax.swing.JTextArea txtAreaPainel;
    private javax.swing.JScrollPane txtPainel;
    // End of variables declaration//GEN-END:variables
}
