/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

import br.com.ifba.atividade09.classe.PagamentoCartao;
import br.com.ifba.atividade09.classe.PagamentoDinheiro;
import br.com.ifba.atividade09.classe.PagamentoPix;

/**
 *
 * @author PC
 */
public class CalcularPagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalcularPagamento.class.getName());

    /**
     * Creates new form CalcularPagamento
     */
    public CalcularPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagamento = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblTituloPagamento = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRecibo = new javax.swing.JTextArea();
        btnCartao = new javax.swing.JRadioButton();
        btnDinheiro = new javax.swing.JRadioButton();
        btnPix = new javax.swing.JRadioButton();
        lblFormaTitulo = new javax.swing.JLabel();
        lblTotalPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Calculo de Pagamento");

        lblTituloPagamento.setText("Valor do pagamnto");

        txtValor.setText("0");
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        txtAreaRecibo.setColumns(20);
        txtAreaRecibo.setRows(5);
        jScrollPane1.setViewportView(txtAreaRecibo);

        formaPagamento.add(btnCartao);
        btnCartao.setText("Cartão");
        btnCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartaoActionPerformed(evt);
            }
        });

        formaPagamento.add(btnDinheiro);
        btnDinheiro.setText("Dinheiro");
        btnDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDinheiroActionPerformed(evt);
            }
        });

        formaPagamento.add(btnPix);
        btnPix.setText("Pix");

        lblFormaTitulo.setText("Forma de pagamento");

        lblTotalPago.setText("Total Pago:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloPagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalPago)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(btnPagar))
                                    .addComponent(btnDinheiro)
                                    .addComponent(btnCartao)
                                    .addComponent(btnPix)
                                    .addComponent(lblFormaTitulo))
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloPagamento)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPago))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(lblFormaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCartao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPix)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagar)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        PagamentoCartao cartao = new PagamentoCartao();
        PagamentoDinheiro dinheiro = new PagamentoDinheiro();
        PagamentoPix pix = new PagamentoPix();
        
        if(btnDinheiro.isSelected()){
            lblTotalPago.setText("Total pago:" + dinheiro.calcularTotal(Double.parseDouble(txtValor.getText())));
            txtAreaRecibo.setText(dinheiro.imprimirRecibo(Double.parseDouble(txtValor.getText())));
        }else if(btnCartao.isSelected()){
            lblTotalPago.setText("Total pago:" + cartao.calcularTotal(Double.parseDouble(txtValor.getText())));
            txtAreaRecibo.setText(cartao.imprimirRecibo(Double.parseDouble(txtValor.getText())));
        }else if(btnPix.isSelected()){
            lblTotalPago.setText("Total pago:" + pix.calcularTotal(Double.parseDouble(txtValor.getText())));
            txtAreaRecibo.setText(pix.imprimirRecibo(Double.parseDouble(txtValor.getText())));
        }else{
            lblTotalPago.setText("Total pago: ERRO");
        }
        
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCartaoActionPerformed

    private void btnDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDinheiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalcularPagamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCartao;
    private javax.swing.JRadioButton btnDinheiro;
    private javax.swing.JButton btnPagar;
    private javax.swing.JRadioButton btnPix;
    private javax.swing.ButtonGroup formaPagamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormaTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPagamento;
    private javax.swing.JLabel lblTotalPago;
    private javax.swing.JTextArea txtAreaRecibo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
